
### criando os companias
POST http://localhost:3000/company HTTP/1.1
content-type: application/json

{
  "name":         "Neres Pao",
  "type":         "Pão",
  "description":  "Pão de forma fresco e saboroso",
  "url_img":      "https://example.com/nere-pao.jpg"
}


### Listar todos as companias.
GET http://localhost:3000/company HTTP/1.1
content-type: application/json


### busca apens um ususario
GET http://localhost:3000/company/id HTTP/1.1
content-type: application/json

