 ### criando os pagamentos
POST http://localhost:3000/payment HTTP/1.1
content-type: application/json

{
    "companyId":1,
    "value":20.0,      
    "method":"pix",  
    "toDate":"2026-04-08T00:00:01.000Z",       
    "dueDate":"2026-04-10T00:00:00.000Z",        
    "userId":1
}

### Listar todos os pagamentos

GET https://projeto-integrador-fiado.onrender.com/payment HTTP/1.1
content-type: application/json


### mostrar

GET https://projeto-integrador-fiado.onrender.com/payment/value_min?=10&value_max=60 HTTP/1.1
Content-type: application/json

### mostrar

GET https://projeto-integrador-fiado.onrender.com/payment/ HTTP/1.1
Content-type: application/json

###
GET https://projeto-integrador-fiado.onrender.com/payment/userId?=2 HTTP/1.1
Content-type: application/json

### 

PUT  https://projeto-integrador-fiado.onrender.com/payment/1 HTTP/1.1
Content-type: application/json

{
    "companyId":1,
    "value":200.0,      
    "method":"boleto",  
    "toDate":"2020-01-01T00:00:00.000Z",       
    "dueDate":"2022-01-02T00:00:00.000Z",        
    "userId":1
}


###
DELETE https://projeto-integrador-fiado.onrender.com/payment/1 HTTP/1.1
Content-type: application/json


