@emailLogin = admin@admin
@senhaLogin = admin

@baseUrl = https://projeto-integrador-fiado.onrender.com

//@baseUrl = http://localhost:3000

### Fazer o login
# @name realizarLogin
POST {{baseUrl}}/user/login HTTP/1.1
content-type: application/json

{
  "email": "{{emailLogin}}",
  "senha": "{{senhaLogin}}"
}

### Salva o Token Globalmente
@authToken = {{realizarLogin.response.body.token}}



--------------------------------------------------------------------------

### criando os produtos
POST {{baseUrl}}/product HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "value": 20.00,
  "name": "batata frita",
  "type": "comida",
  "description": "batata frita",
  "url_img": "https://example.com/image2.jpg"
}

### Listar todos os produtos
GET {{baseUrl}}/product HTTP/1.1
Content-Type: application/json


### Buscar produto por TIPO
GET {{baseUrl}}/product?type=comida HTTP/1.1
Content-Type: application/json


###editando produtos
PUT {{baseUrl}}/product/15 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{  
  "value": 10.00,
  "name": "milena Produto 3",
  "type": "bola",
  "description": "Descrição do produto 3",
  "url_img": "https://example.com/image2.jpg"
}

### deletando Produto
DELETE {{baseUrl}}/product/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}