### criando um login e senha
# @name loginRequest
POST https://projeto-integrador-fiado.onrender.com/user/login HTTP/1.1  
Content-Type: application/json

{
    "email": "teste@gmail.com",
    "senha": "12345"
}

###
@token = {{loginRequest.response.body.token}}

### criando os produtos
POST https://projeto-integrador-fiado.onrender.com/product HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "companyId":1,
  "value": 20.00,
  "name": "Produto 2",
  "type": "bike",
  "description": "Descrição do produto 2",
  "url_img": "https://example.com/image2.jpg"
}

### Listar todos os produtos
GET https://projeto-integrador-fiado.onrender.com/product HTTP/1.1
Content-Type: application/json


### Buscar produto por id
GET https://projeto-integrador-fiado.onrender.com/product?type=bike HTTP/1.1
Content-Type: application/json

###editando todos os campos dos produtos

PUT https://projeto-integrador-fiado.onrender.com/product/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  
  "value": 10.00,
  "name": "milena Produto 3",
  "type": "bola",
  "description": "Descrição do produto 3",
  "url_img": "https://example.com/image2.jpg"
}

### deletando um usuario

DELETE https://projeto-integrador-fiado.onrender.com/product/16 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}