
### criando um usuario
POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
  "name": "milena",
  "type": "pizzariateste",
  "email":"milena@gmail.com",
  "senha":"12345"
}

### Listar todos os usuarios

GET http://localhost:3000/user HTTP/1.1
content-type: application/json

### busca apens um usuario

GET http://localhost:3000/user/2 HTTP/1.1
content-type: application/json

### buscar por nome

GET http://localhost:3000/user?name=teste HTTP/1.1
content-type: application/json

### buscar por type

GET http://localhost:3000/user?type=bo HTTP/1.1
content-type: application/json

### edita user 

PUT http://localhost:3000/user/1 HTTP/1.1
content-type: application/json

{
  "name": "camila cristina",
  "type": "pizzariateste",
  "email":"camila@gmail.com",
  "senha":"batata01"
}
