
### criando um usuario
POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
  "name": "milena",
  "type": "pizzariateste",
  "email":"milena@gmail.com",
  "senha":"12345"
}

### Listar todos os usuarios

GET http://localhost:3000/user HTTP/1.1
content-type: application/json

### busca apens um ususario

GET http://localhost:3000/user/1 HTTP/1.1
content-type: application/json
