@baseUrl = {{baseUrl}}
@emailLogin = superowner@gmail.com
@senhaLogin = 1234

### Login (Servirá apenas para puxar o token automaticamente para as rotas abaixo)
# @name realizarLogin
POST {{baseUrl}}/user/login HTTP/1.1
content-type: application/json

{
  "email": "{{emailLogin}}",
  "senha": "{{senhaLogin}}"
}

### Salva o Token Globalmente
@authToken = {{realizarLogin.response.body.token}}


# =========================================================
# CRIAR NOVO USUÁRIO (Requer Autenticação se for criar Admin)
# =========================================================

### criando um usuario admin (Apenas se o token logado for admin)
POST {{baseUrl}}/user HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "name": "superowner",
  "email":"superowner@gmail.com",
  "senha":"1234",
  "type":"userOwner"
}


# =========================================================
# ROTAS PROTEGIDAS (Ver, Editar, Deletar)
# =========================================================

### Listar todos os usuarios (Bloqueado para usuários comuns)
GET {{baseUrl}}/user HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

### Listar apenas userOwner (usuários que possuem empresa vinculada)
GET {{baseUrl}}/user?type=userOwner HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

### Listar apenas userClient (usuários sem empresa vinculada)
GET {{baseUrl}}/user?type=userClient HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

### buscar apenas um usuario (Qualquer um acessa SEU próprio perfil, admin acessa todos)
GET {{baseUrl}}/user/1 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

### buscar por nome
GET {{baseUrl}}/user?name=teste HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

### edita user (NÃO MUDAR TYPE AQUI, APENAS NA CRIAÇÃO)
PUT {{baseUrl}}/user/1 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
  "name": "camila cristina",
  "email":"camila@gmail.com",
  "senha":"batata01"
}

### deleta um usuario
DELETE {{baseUrl}}/user/6 HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json


